// app-react/src/layouts/header/index.jsx
import { Link } from "react-router-dom";
import "./style.css"

export default function Header() {
  return (
    <header className="header">
      <nav>
        <ul>
          <li>
            <Link to={`/`}>
              Tarefas
            </Link>
          </li>
          <li>
            <Link to={`/users`}>
              Usuários
            </Link>
          </li>
          <li>
            <Link to={`/comments`}>
              Comentários
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  )
}

// app-vue/src/components/Header.vue
<template>
  <header>
    <nav>
      <ul>
        <li>
          <router-link to="/"> Tarefas </router-link>
        </li>
        <li>
          <router-link to="/users"> Usuários </router-link>
        </li>
        <li>
          <router-link to="/comments"> Comentários </router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: "Header",
};
</script>

<style scoped>
</style>
